<div class="row">
	<div class="span12">
		<ul class="breadcrumb">
			<li>
				<a href="<?php echo site_url('creintech') ?>">Principal</a> <span class="divider">/</span>
			</li>					
			<li class="active">Estudios</li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="span12">								
		<h4>DIAGNÓSTICO TÉCNICO DE LOS SISTEMAS DE GESTIÓN DE RESIDUOS DE CINCO MUNICIPIOS DE LA REGIÓN CAPITAL DEL ESTADO DE VERACRUZ</h4>		        
        <p>Los residuos sólidos urbanos se definen como aquellos generados en las casas habitación, que resultan de la eliminación de los materiales que utilizan en sus actividades domésticas, de los productos que consumen y de sus envases, embalajes o empaques; los residuos que provienen de cualquier otra actividad dentro de establecimientos o en la vía pública que genere residuos con características domiciliarias, y los resultantes de la limpieza de las vías y lugares públicos, esto según la Ley General para la Prevención y Gestión Integral de los Residuos, publicada en el 2003, lo anterior, prácticamente incluye a la mayoría de los residuos que se generan diariamente en cada una de las actividades que se desarrollan en la sociedad en general.</p>
        <p>La composición de los RSU se ve influenciada por factores como el nivel socieconómico, temporada del año, actividades económicas desarrolladas donde se generen los residuos, los materiales pueden clasificarse típicamente en dos tipos como son los residuos orgánicos (excedentes de comida y restos de material vegetal), papel, cartón, madera y en general materiales biodegradables e inorgánicos como, vidrio, plástico, metales y material inerte. (SEMARNAT, 2001)</p>
        <p>En México se recolectaba en el año 2000 el 83% del total de los residuos generados (69,886 toneladas) y quedaban dispersas diariamente 14,314 toneladas. Del total generado, poco más del 49% se depositaban en sitios controlados, esto es, 41,258 toneladas por día, lo que significa que 42,942 toneladas se disponían diariamente a cielo abierto, en tiraderos no controlados, tiraderos clandestinos o dispersos de forma inadecuada. De seguir esa tendencia, la situación de por sí ya grave, puede adquirir un perfil crítico. (SEMARNAT, 2001)</p>
        <p>Según datos de la SEDESOL, en 2004 la generación de residuos sólidos urbanos fue de 94,800 toneladas diarias, equivalentes a 34.6 millones de toneladas anuales en todo el país Para México, como en muchos otros países del mundo, la gestión integral de los residuos representa una problemática pues la generación y composición de los residuos ha variado significativamente durante las últimas décadas, derivado del desarrollo del país, así como del incremento poblacional y los cambios en los patrones de urbanización, en este sentido se ha observado que la generación per cápita creció 300 gr/día en 1950 a 900 gr/día en 2004. Una proyección al año 2020, indica que la generación per-cápita de RSU será de 1,060 gr/día</p>
        <p>La importancia del problema, radica en que la mayoría de los residuos son enviados en el mejor de los casos a rellenos sanitarios que por normatividad tienen un mejor control; sin embargo, en muchos otros casos, los residuos son enviados a tiraderos a cielo abierto o vertederos clandestinos, mismos que son fuente de contaminación a la atmósfera y a través de los lixiviados que se generan, incrementan la contaminación en mantos freáticos y suelos.</p>
        <p>Generalmente los sistemas de gestión integral están enfocados a obtener un máximo aprovechamiento de los residuos, lo que sugiere el envío a disposición final de aquellos materiales que no pueden ser recuperados e integrados a ciclos productivos; sin embargo, son muy pocas las medidas aplicadas para la separación de residuos desde su origen, todo ello se refleja en las cantidades de materiales aprovechables que son enviados a los sistemas de recolección y que no logran separarse en su totalidad, generando una saturación prematura de los rellenos sanitarios, esto, sin contar que en algunos de los casos lo residuos son colocados en tiraderos a cielo abierto y causando un mayor impacto al entorno.</p>
		<p><a class="btn" href="<?php echo base_url(); ?>documentos/analisis/diagnostico1.pdf" target="_new">Ver Documento &raquo;</a></p>
	</div>
</div>				