<div class="row">
	<div class="span12">
		<ul class="breadcrumb">
			<li>
				<a href="<?php echo site_url('creintech') ?>">Principal</a> <span class="divider">/</span>
			</li>					
			<li class="active">Estudios</li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="span12">								
		<h4>CARACTERIZACIÓN DE LOS RESIDUOS SÓLIDOS URBANOS DEL MUNICIPIO DE BANDERILLA, VERACRUZ.</h4>		        
        <p>El presente reporte contiene los resultados obtenidos de las caracterizaciones realizadas los días 22 de octubre y 6 de noviembre del 2013 en las instalaciones de la antigua calera, área que las autoridades municipales destinaron para dicho proceso; los muestreos que se llevaron a cabo forman parte de una serie de actividades desarrolladas en el marco del proyecto apoyado por el Consejo Nacional de Ciencia y Tecnología y la Secretaría de Economía, denominado “Desarrollo de un modelo de innovación tecnológica para el manejo integral de residuos sólidos urbanos en la región capital del estado de Veracruz”, que está orientado a la implementación de nuevas tecnologías que permitan una mejor disposición de los residuos sólidos. Por lo anterior, se hizo prioritaria la elaboración de los diagnósticos básicos de los residuos sólidos en los municipios de Banderilla, Coatepec, Emiliano Zapata, Perote y Xalapa, con la finalidad de obtener un marco referencial de la situación del manejo y disposición de los residuos en cada municipio, así como detectar los volúmenes de material con potencial para el reciclaje que son enviados a los sitios de disposición final.</p>
		<p>Como información adicional, se muestra un breve estudio comparativo de los resultados obtenidos en los municipios participantes, haciendo de su conocimiento la situación regional en cuanto a la composición de los residuos sólidos urbanos y que será útil para las iniciativas planteadas en el proyecto antes mencionado.</p>
		<p><a class="btn" href="<?php echo base_url(); ?>documentos/analisis/estudio1.pdf" target="_new">Ver Documento &raquo;</a></p>
                <hr>
                <h4>CARACTERIZACIÓN DE LOS RESIDUOS SÓLIDOS URBANOS DEL MUNICIPIO DE COATEPEC, VERACRUZ.</h4>
                <p>El presente reporte contiene los resultados obtenidos de las caracterizaciones realizadas en el mes de noviembre en la estación de transferencia de iniciativa privada y en el que se reciben residuos provenientes del municipio de Coatepec; dichos muestreos forman parte de una serie de actividades desarrolladas en el marco del proyecto apoyado por el Consejo Nacional de Ciencia y Tecnología y la Secretaría de Economía, denominado “Desarrollo de un modelo de innovación tecnológica para el manejo integral de residuos sólidos urbanos en la región capital del estado de Veracruz”, que está orientado a la implementación de nuevas tecnologías que permitan una mejor disposición de los residuos sólidos. Por lo anterior, se hizo prioritaria la elaboración de los diagnósticos básicos de los residuos sólidos en los municipios de Banderilla, Coatepec, Emiliano Zapata, Perote y Xalapa, con la finalidad de obtener un marco referencial de la situación del manejo y disposición de los residuos en cada municipio, así como detectar los volúmenes de material con potencial para el reciclaje que son enviados a los sitios de disposición final.</p>
                <p>Como información adicional, se muestra un breve estudio comparativo de los resultados obtenidos en los municipios participantes, haciendo de su conocimiento la situación regional en cuanto a la composición de los residuos sólidos urbanos y que será útil para las iniciativas planteadas en el proyecto antes mencionado.</p>
                <p><a class="btn" href="<?php echo base_url(); ?>documentos/analisis/estudio2.pdf" target="_new">Ver Documento &raquo;</a></p>
                <hr>
                <h4>CARACTERIZACIÓN DE LOS RESIDUOS SÓLIDOS URBANOS DEL MUNICIPIO DE PEROTE, VERACRUZ.</h4>
                <p>El presente reporte contiene los resultados obtenidos de las caracterizaciones realizadas el día 19 de noviembre en el lugar que se ha destinado para la disposición de los residuos del municipio de Perote; dichos muestreos forman parte de una serie de actividades desarrolladas en el marco del proyecto apoyado por el Consejo Nacional de Ciencia y Tecnología y la Secretaría de Economía, denominado “Desarrollo de un modelo de innovación tecnológica para el manejo integral de residuos sólidos urbanos en la región capital del estado de Veracruz”, que está orientado a la implementación de nuevas tecnologías que permitan una mejor disposición de los residuos sólidos. Por lo anterior, se hizo prioritaria la elaboración de los diagnósticos básicos de los residuos sólidos en los municipios de Banderilla, Coatepec, Emiliano Zapata, Perote y Xalapa, con la finalidad de obtener un marco referencial de la situación del manejo y disposición de los residuos en cada municipio, así como detectar los volúmenes de material con potencial para el reciclaje que son enviados a los sitios de disposición final.</p>
                <p>Como información adicional, se muestra un breve estudio comparativo de los resultados obtenidos en los municipios participantes, haciendo de su conocimiento la situación regional en cuanto a la composición de los residuos sólidos urbanos y que será útil para las iniciativas planteadas en el proyecto antes mencionado.</p>
                <p><a class="btn" href="<?php echo base_url(); ?>documentos/analisis/estudio3.pdf" target="_new">Ver Documento &raquo;</a></p>
                <hr>
                <h4>CARACTERIZACIÓN DE LOS RESIDUOS SÓLIDOS URBANOS DEL MUNICIPIO DE XALAPA, VERACRUZ.</h4>
                <p>El presente reporte contiene los resultados obtenidos de las caracterizaciones realizadas los días 3 y 4 de diciembre en el relleno sanitario ubicado en la localidad de Tronconal; las cuales forman parte de una serie de actividades desarrolladas en el marco del proyecto apoyado por el Consejo Nacional de Ciencia y Tecnología y la Secretaría de Economía, denominado “Desarrollo de un modelo de innovación tecnológica para el manejo integral de residuos sólidos urbanos en la región capital del estado de Veracruz”, que está orientado a la implementación de nuevas tecnologías que permitan una mejor disposición de los residuos sólidos. Por lo anterior, se hizo prioritaria la elaboración de los diagnósticos básicos de los residuos sólidos en los municipios de Banderilla, Coatepec, Emiliano Zapata, Perote y Xalapa, con la finalidad de obtener un marco referencial de la situación del manejo y disposición de los residuos en cada municipio, así como detectar los volúmenes de material con potencial para el reciclaje que son enviados a los sitios de disposición final.</p>
                <p>Como información adicional, se muestra un breve estudio comparativo de los resultados obtenidos en los municipios participantes, haciendo de su conocimiento la situación regional en cuanto a la composición de los residuos sólidos urbanos y que será útil para las iniciativas planteadas en el proyecto antes mencionado.</p>
                <p><a class="btn" href="<?php echo base_url(); ?>documentos/analisis/estudio4.pdf" target="_new">Ver Documento &raquo;</a></p>
	</div>
</div>				